services:
  # 1. Database එක ඇඩ් කළා
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

  # 2. Backend එක නිවැරදි කළා
  backend:
    build: ./backend
    container_name: smart-operation-hub-backend
    ports:
      - "8082:8082"
    # volumes: - ./backend:/app  <-- මේක අයින් කළා, නැත්නම් app.jar එක නැති වෙනවා
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/CampusHubDB
    networks:
      - app-network

  # 3. Frontend එක
  frontend:
    build: ./frontend 
    container_name: smart-operation-hub-frontend
    ports:
      - "5174:5173"
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge